### ISSUE TITLE
Fails to open 3.10 cpython objects inventory

### ISSUE THREAD

**Issue by gaborbernat** [bskinn/sphobjinv#208]
```
curl -s https://docs.python.org/3.9/objects.inv 1>out.inv

sphobjinv suggest ./out.inv Type

Traceback (most recent call last):
  File "/Users/bgabor8/.local/bin/sphobjinv", line 8, in <module>
    sys.exit(main())
  File "/Users/bgabor8/.local/pipx/venvs/sphobjinv/lib/python3.10/site-packages/sphobjinv/cli/core.py", line 208, in main
    inv, in_path = inv_local(params)
  File "/Users/bgabor8/.local/pipx/venvs/sphobjinv/lib/python3.10/site-packages/sphobjinv/cli/load.py", line 115, in inv_local
    inv = import_infile(in_path)
  File "/Users/bgabor8/.local/pipx/venvs/sphobjinv/lib/python3.10/site-packages/sphobjinv/cli/load.py", line 64, in import_infile
    inv = Inventory(in_path)
  File "<attrs generated init sphobjinv.inventory.Inventory>", line 16, in __init__
  File "/Users/bgabor8/.local/pipx/venvs/sphobjinv/lib/python3.10/site-packages/sphobjinv/inventory.py", line 350, in __attrs_post_init__
    self._general_import()
  File "/Users/bgabor8/.local/pipx/venvs/sphobjinv/lib/python3.10/site-packages/sphobjinv/inventory.py", line 594, in _general_import
    raise TypeError("Invalid Inventory source type")
TypeError: Invalid Inventory source type
```

**Comment by bskinn** [comment]
First guess is an encoding problem with `curl ... > out.inv`.

What happens if you `wget` the inventory, instead?

Or, try `sphobjinv suggest -u {URL} Type`.
